# Generated by Django 3.2.6 on 2021-10-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbsCrypto',
            fields=[
                ('crypto_name', models.CharField(max_length=255)),
                ('pk_crypto_code', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TBS_Crypto',
            },
        ),
        migrations.CreateModel(
            name='TblHistCryptoDaily',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('fk_crypto_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tbscrypto')),
            ],
            options={
                'db_table': 'TBL_Hist_Crypto',
            },
        ),
    ]
